{
 "title": "Solar Power Dashboard",
 "time": { "from": "now-1s", "to": "now" },
 "panels": [
  {
   "title": "Load Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") AS \"value\"\nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/total\\/load_power\\/state/\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Solar PV Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nSELECT last(\"value\") AS \"value\"\nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/total\\/pv_power\\/state/\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nSELECT last(\"value\") AS \"value\"\nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/total\\/battery_power\\/state/\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Grid Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nSELECT last(\"value\") AS \"value\"\nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/total\\/grid_power\\/state/\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") AS \"value\"\nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/total\\/battery_state_of_charge\\/state/\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nSELECT last(\"value\") AS \"value\"\nFROM \"state\"\nWHERE \"topic\" =~  /.+\\/inverter_\\d+\\/battery_voltage\\/state/\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nSELECT last(\"value\") AS \"value\"\nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/total\\/grid_voltage\\/state/\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "W" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") AS \"Battery power\" FROM \"state\" WHERE \"topic\" =~ /.+\\/total\\/battery_power\\/state/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Battery state of charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") AS \"Battery state of charge\" FROM \"state\" WHERE \"topic\" =~ /.+\\/total\\/battery_state_of_charge\\/state/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}